name: vsynth
channels:
  - conda-forge
  - microsoft
dependencies:
  - python=3.11.4
  - pip
  - ipykernel
  - pandas
  - numpy
  - scikit-learn
  - ctgan
  - matplotlib
  - python-dotenv
  - tensorflow-gpu
  - sdv
  - azure-storage-blob
  - cudatoolkit=11.8.0
  - statsmodels
  - pydantic=2.6.1
  - pydantic-settings=2.1.0
